version: "3"

services:

# ------> adminer ------>
    adminer_fg2kvjo4y8cw5:
        container_name: adminer_fg2kvjo4y8cw5
        image: adminer:latest
        restart: always
        environment:
            ADMINER_PLUGINS: tables-filter tinymce
            ADMINER_DESIGN: pepa-linha
        ports:
            - 8080:8080
# <------ adminer <------

# ------> django ------>
    django_fg2kvjo4y8cw6:
        container_name: django_fg2kvjo4y8cw6
        build: ./django
        restart: always
        volumes:
            - ../:/app
        ports:
            - 8000:8000
        depends_on:
            - postgres_fg2kvjo4y8cw7
        command: bash -c "python3 manage.py runserver 0.0.0.0:8000 && python3 manage.py loaddata card"
# <------ django <------

# ------> postgres ------>
    postgres_fg2kvjo4y8cw7:
        container_name: postgres_fg2kvjo4y8cw7
        image: postgres:10
        restart: always
        environment:
            POSTGRES_USER: skyflow
            POSTGRES_PASSWORD: root
            POSTGRES_DB: skyflow
        ports:
            - 5432:5432
        volumes:
            - ../../.database/my_app:/var/lib/postgresql/data
# <------ postgres <------