# Generated by Django 2.2.dev20190108231243 on 2019-01-09 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
