# Generated by Django 2.2.dev20190108191513 on 2019-01-08 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hearthstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='En attente', max_length=150)),
                ('card1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_1_exchange', to='hearthstone.Card')),
                ('card2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_2_exchange', to='hearthstone.Card')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1_exchange', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2_exchange', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
