# Generated by Django 2.2.dev20190107231812 on 2019-01-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0002_auto_20190107_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.CreateModel(
            name='CardsDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='pack',
            field=models.ManyToManyField(related_name='pack', through='hearthstone.CardsDeck', to='hearthstone.Deck'),
        ),
    ]
