# Generated by Django 2.2.dev20190109093221 on 2019-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0002_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='user1_response',
            field=models.CharField(blank=True, default='En attente', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='exchange',
            name='user2_response',
            field=models.CharField(blank=True, default='En attente', max_length=150, null=True),
        ),
    ]
