# Generated by Django 2.2.dev20181007223708 on 2018-10-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0004_auto_20181013_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.CreateModel(
            name='Card_Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hearthstone.Deck')),
            ],
        ),
    ]
