# Generated by Django 2.2.dev20181007223708 on 2018-10-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0005_auto_20181013_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
