# Generated by Django 2.2.dev20190106020926 on 2019-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hearthstone', '0006_activity_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
